export class tbl_Employee {
  public id: number;
  public name: string;
  public userID: number;
  public firstName: string;
  public middleName: string;
  public lastName: string;
  public gender: string;
  public cnic: string;
  public birthDate: Date;
  public bloodGroup: string;
  public fullAddress: string;
  public email: string;
  public homePhone: string;
  public cellPhone: string;
  public imageUrl: string;
  public seriesID: number;
  public deptID: string;
  public jobTitleID: string;
  public jobStatusID: string;
  public experiance: string;
  public hireDate: Date;
  public workShiftID: string;
  public isActive: boolean;
  public organizationID: number;
  public legalEntityID: number;
  public branchID: number;
  public locationID: number;
  public cutOffTime: string;
  public isOverTime: boolean;
  public includeCutOffTime: boolean;
  public statusID: number;
  public gracePeriod: string;
  public probationPeriod: number;
  public androidService: boolean;
  public isAutoAttendance: boolean;
  public confirmationDate: Date;
  public contractExpiryDate: Date;
  public contractDaysForEmail: number;
  public nicExpiryDate: Date;
  public fathersName: string;
  public religion: string;
  public birthPlace: string;
  public nationality: string;
  public permanentAddress: string;
  public spouseName: string;
  public noOfDependents: number;
  public spouseBirthDate: Date;
  public dateOfWedding: Date;
  public spouseContactDetails: string;
  public maritalStatus: number;
  public stopSalary: boolean;
  public isReHire: boolean;
  public retirementDate: Date;
  public gradeID: number;
  public isOvertimeAfterShiftTime: boolean;
  public honorific: string;
  public employementFileNumber: string;
  public wfhRequest: string;
  public autoCheckOut: boolean;
  public autoCheckOutTime: string;
  public physicalFitness: string;
  public managementCadreID: number;

  constructor() {
    this.id = 0;
    this.name = "";
    this.userID = 0;
    this.firstName = "";
    this.middleName = "";
    this.lastName = "";
    this.gender = "";
    this.cnic = "";
    this.birthDate = new Date();
    this.bloodGroup = "";
    this.fullAddress = "";
    this.email = "";
    this.homePhone = "";
    this.cellPhone = "";
    this.imageUrl = "";
    this.seriesID = 0;
    this.deptID = "";
    this.jobTitleID = "";
    this.jobStatusID = "";
    this.experiance = "";
    this.hireDate = new Date();
    this.workShiftID = "";
    this.isActive = false;
    this.organizationID = 0;
    this.legalEntityID = 0;
    this.branchID = 0;
    this.locationID = 0;
    this.cutOffTime = "";
    this.isOverTime = false;
    this.includeCutOffTime = false;
    this.statusID = 0;
    this.gracePeriod = "";
    this.probationPeriod = 0;
    this.androidService = false;
    this.isAutoAttendance = false;
    this.confirmationDate = new Date();
    this.contractExpiryDate = new Date();
    this.contractDaysForEmail = 0;
    this.nicExpiryDate = new Date();
    this.fathersName = "";
    this.religion = "";
    this.birthPlace = "";
    this.nationality = "";
    this.permanentAddress = "";
    this.spouseName = "";
    this.noOfDependents = 0;
    this.spouseBirthDate = new Date();
    this.dateOfWedding = new Date();
    this.spouseContactDetails = "";
    this.maritalStatus = 0;
    this.stopSalary = false;
    this.isReHire = false;
    this.retirementDate = new Date();
    this.gradeID = 0;
    this.isOvertimeAfterShiftTime = false;
    this.honorific = "";
    this.employementFileNumber = "";
    this.wfhRequest = "";
    this.autoCheckOut = false;
    this.autoCheckOutTime = "";
    this.physicalFitness = "";
    this.managementCadreID = 0;
  }
}
