import { tbl_EmployeeKins } from "../Tables/tbl-employee-kins.model";
import { tbl_EmployeeEmergencyContact, tbl_EmployeeQualifications } from "../Tables/tbl-employee-qualifications.model";
import { tbl_Machines } from "../Tables/tbl-machines.model";

export class req_Employee {
  id: number;
  name: string;
  userId: number;
  userName: string;
  password: string;
  isWebLogin: boolean;
  domain: string;
  softwareRoleId: number;
  firstName: string;
  middleName: string;
  lastName: string;
  gender: string;
  cnic: string;
  birthDate: Date | null;
  bloodGroup: string;
  fullAddress: string;
  email: string;
  homePhone: string;
  cellPhone: string;
  imageUrl: string;
  coverImageUrl: string;
  employeeNo: number;
  reportingTo: number;
  secondaryReportingTo: number;
  deptId: number;
  mainDeptId: number;
  jobTitleId: number;
  jobStatusId: number;
  experiance: string;
  designation: string;
  department: string;
  hireDate: Date | null;
  workShiftId: number;
  isActive: boolean;
  accountId: number;
  organizationId: number;
  legalEntityId: number;
  branchId: number;
  locationId: number;
  legalEntityIds: string;
  branchIds: string;
  locationIds: string;
  jobTypeId: number;
  cutOffTime: string | null;
  cutOffTimeDatetime: Date | null;
  isOverTime: boolean;
  includeCutOffTime: boolean;
  statusId: number;
  gracePeriodDatetime: Date | null;
  probationPeriod: number;
  androidService: boolean;
  authorizationCode: string;
  allowCheckIn: boolean;
  isAutoAttendance: boolean;
  confirmationDate: Date | null;
  contractExpiryDate: Date | null;
  contractDaysForEmail: number;
  nicExpiryDate: Date | null;
  fathersName: string;
  religion: string;
  birthPlace: string;
  nationality: string;
  permanentAddress: string;
  spouseName: string;
  noOfDependents: number;
  spouseBirthDate: Date | null;
  dateOfWedding: Date | null;
  spouseContactDetails: string;
  emergencyNameOne: string;
  emergencyAddressOne: string;
  emergencyCellPhoneOne: string;
  emergencyNameTwo: string;
  emergencyAddressTwo: string;
  emergencyCellPhoneTwo: string;
  maritalStatus: number;
  maritalStatusDetail: string;
  stopSalary: boolean;
  isReHire: boolean;
  retirementDate: Date | null;
  gradeId: number;
  isOvertimeAfterShiftTime: boolean;
  honorific: string;
  apiKey: string;
  employementFileNumber: string;
  wfhRequest: string;
  autoCheckOut: boolean;
  autoCheckOutTime: string;
  physicalFitness: string;
  managementCadreId: number;
  createdBy: number;
  gracePeriod: string | null;
  kids: tbl_EmployeeKins[];
  qualifications: tbl_EmployeeQualifications[];
  machines: tbl_Machines[];
  emergencyContacts: tbl_EmployeeEmergencyContact[];
  userMappingDetails: string;
  emergencyDetails: string;
  kidsInfo: string;
  qualificationDetails: string;
  softwareRole: string;
  organizationCode: string;
  legalEntity: string;
  branch: string;
  location: string;
  jobType: string;
  workShift: string;
  pageId: number;
  reportingBossName: string;
  secondaryReportingName: string;
  subordinates: string;
  timeSheetRuleId: number;
  timeSheetRule: string;

  constructor() {
    this.id = 0;
    this.name = '';
    this.userId = 0;
    this.userName = '';
    this.password = '';
    this.isWebLogin = false;
    this.domain = '';
    this.softwareRoleId = 0;
    this.firstName = '';
    this.middleName = '';
    this.lastName = '';
    this.gender = '';
    this.cnic = '';
    this.birthDate = null;
    this.bloodGroup = '';
    this.fullAddress = '';
    this.email = '';
    this.homePhone = '';
    this.cellPhone = '';
    this.imageUrl = '';
    this.coverImageUrl = '';
    this.employeeNo = 0;
    this.reportingTo = 0;
    this.secondaryReportingTo = 0;
    this.deptId = 0;
    this.mainDeptId = 0;
    this.jobTitleId = 0;
    this.jobStatusId = 0;
    this.experiance = '';
    this.designation = '';
    this.department = '';
    this.hireDate = null;
    this.workShiftId = 0;
    this.isActive = false;
    this.accountId = 0;
    this.organizationId = 0;
    this.legalEntityId = 0;
    this.branchId = 0;
    this.locationId = 0;
    this.legalEntityIds = '';
    this.branchIds = '';
    this.locationIds = '';
    this.jobTypeId = 0;
    this.cutOffTime = null;
    this.cutOffTimeDatetime = null;
    this.isOverTime = false;
    this.includeCutOffTime = false;
    this.statusId = 0;
    this.gracePeriodDatetime = null;
    this.probationPeriod = 0;
    this.androidService = false;
    this.authorizationCode = '';
    this.allowCheckIn = false;
    this.isAutoAttendance = false;
    this.confirmationDate = null;
    this.contractExpiryDate = null;
    this.contractDaysForEmail = 0;
    this.nicExpiryDate = null;
    this.fathersName = '';
    this.religion = '';
    this.birthPlace = '';
    this.nationality = '';
    this.permanentAddress = '';
    this.spouseName = '';
    this.noOfDependents = 0;
    this.spouseBirthDate = null;
    this.dateOfWedding = null;
    this.spouseContactDetails = '';
    this.emergencyNameOne = '';
    this.emergencyAddressOne = '';
    this.emergencyCellPhoneOne = '';
    this.emergencyNameTwo = '';
    this.emergencyAddressTwo = '';
    this.emergencyCellPhoneTwo = '';
    this.maritalStatus = 0;
    this.maritalStatusDetail = '';
    this.stopSalary = false;
    this.isReHire = false;
    this.retirementDate = null;
    this.gradeId = 0;
    this.isOvertimeAfterShiftTime = false;
    this.honorific = '';
    this.apiKey = '';
    this.employementFileNumber = '';
    this.wfhRequest = '';
    this.autoCheckOut = false;
    this.autoCheckOutTime = '';
    this.physicalFitness = '';
    this.managementCadreId = 0;
    this.createdBy = 0;
    this.gracePeriod = null;
    this.kids = [];
    this.qualifications = [];
    this.machines = [];
    this.emergencyContacts = [];
    this.userMappingDetails = '';
    this.emergencyDetails = '';
    this.kidsInfo = '';
    this.qualificationDetails = '';
    this.softwareRole = '';
    this.organizationCode = '';
    this.legalEntity = '';
    this.branch = '';
    this.location = '';
    this.jobType = '';
    this.workShift = '';
    this.pageId = 0;
    this.reportingBossName = '';
    this.secondaryReportingName = '';
    this.subordinates = '';
    this.timeSheetRuleId = 0;
    this.timeSheetRule = '';
  }
}
